### ISSUE TITLE
Output is always CRITICAL for SCSI devices

### ISSUE THREAD

**Issue by niccoX** [Elyrith/check_smart#1]
The output is always CRITICAL even though the disk is OK.

**Comment by Elyrith** [comment]
Can you provide a little more info?

I just installed Debian 9.5, updated all packages, installed smartmontools (`sudo apt-get install smartmontools`), then cloned this repo via the HTTP link.

Once I did that I entered the check_smart folder and run `sudo ./check_smart --drive /dev/sda` and it came up with..
`/dev/sda is OK | SMART overall-health self-assessment test result: PASSED`

This matches if I run... `sudo smartctl -d ata -H /dev/sda` and I get...
`SMART overall-health self-assessment test result: PASSED`

**Comment by Elyrith** [comment]
You have to know which drive you are checking. If you don't supply it with a --drive argument it assumes you want /dev/sda. If you don't have a /dev/sda (like HP with /dev/cciss/c0d0) then it won't find /dev/sda and give you a 'CRITICAL' result (which I agree is not correct).

Try running `df -h` and seeing which devices you want to monitor. (Hint: If you have '/dev/sda1' you only want to provide monitor '/dev/sda', since that's the device while '/dev/sda1' is the partition.)

You can also check if SMART is enabled on your device by running `sudo smartctl -i <your device>` which for me gives the following important lines:
> SMART support is: Available - device has SMART capability.
> SMART support is: Enabled

**Comment by niccoX** [comment]
For this drive that needs particular options as `-d scsi` and `-T permissive` to generate an output I end up getting nothing after I run the script after your recent changes.

I tried as well changing the parameters to be inline with the requirements, but still I didn't get anything:

```
#Get the SMART data
smart=$($SENSORPROG -d scsi -T permissive -H "$drive" | grep "result" | cut -d: -f2 | cut -c2-7)

perfdata=$($SENSORPROG -d scsi -T permissive -H "$drive" | grep "result")
```

```
root@tls13:/usr/lib/nagios/plugins# smartctl -d scsi -H /dev/vda -T permissive
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-30-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

Short INQUIRY response, skip product id
=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
```

**Comment by niccoX** [comment]
Want to add that the `Short INQUIRY response, skip product id` usually comes up 95% of the time when I run the command. Which has made some issues with another smart script since it generates a different exit status.

**Comment by Elyrith** [comment]
I'm trying to add an extra `--drive_type` option so you can pass through `scsi`. I'll push an update when I have it working.

**Comment by Elyrith** [comment]
I've created a new branch called new-option. I believe I've gotten it working, but I don't have SCSI, so I can't test that. Please let me know if it works for you.

**Comment by niccoX** [comment]
```
root@tls13:~# ./check_smartmon
root@tls13:~# echo $?
3
```

**Comment by Elyrith** [comment]
Sorry for the delay, but what is check_smartmon?

Are you using https://exchange.nagios.org/directory/Plugins/Operating-Systems/Linux/check_smartmon/details instead?

**Comment by Elyrith** [comment]
Closing since it's been over a year with no update.
